# Configuraci贸n de ambiente de desarrollo
# Primero se carga la configuraci贸n de producci贸n y luego la configuraci贸n de testing que la redefine
imports:
    - { resource: config.prod.yml }
    - { resource: test/parameters.yml }
    - { resource: test/services.yml }
